/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmergenciesRouteImport } from './routes/emergencies'
import { Route as MapRouteImport } from './routes/map'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as CommsIdRouteImport } from './routes/comms.$id'
import { Route as EmergencyIdRouteImport } from './routes/emergency.$id'
import { Route as NavigateIdRouteImport } from './routes/navigate.$id'
import { Route as TimelineIdRouteImport } from './routes/timeline.$id'
import { Route as VictimIdRouteImport } from './routes/victim.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergenciesRoute = EmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsIdRoute = CommsIdRouteImport.update({
  id: '/comms/$id',
  path: '/comms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIdRoute = EmergencyIdRouteImport.update({
  id: '/emergency/$id',
  path: '/emergency/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateIdRoute = NavigateIdRouteImport.update({
  id: '/navigate/$id',
  path: '/navigate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/timeline/$id',
  path: '/timeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VictimIdRoute = VictimIdRouteImport.update({
  id: '/victim/$id',
  path: '/victim/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergencies': typeof EmergenciesRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/comms/$id': typeof CommsIdRoute
  '/emergency/$id': typeof EmergencyIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/timeline/$id': typeof TimelineIdRoute
  '/victim/$id': typeof VictimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergencies': typeof EmergenciesRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/comms/$id': typeof CommsIdRoute
  '/emergency/$id': typeof EmergencyIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/timeline/$id': typeof TimelineIdRoute
  '/victim/$id': typeof VictimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/emergencies': typeof EmergenciesRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/comms/$id': typeof CommsIdRoute
  '/emergency/$id': typeof EmergencyIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/timeline/$id': typeof TimelineIdRoute
  '/victim/$id': typeof VictimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/emergencies'
    | '/map'
    | '/network'
    | '/comms/$id'
    | '/emergency/$id'
    | '/navigate/$id'
    | '/timeline/$id'
    | '/victim/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/emergencies'
    | '/map'
    | '/network'
    | '/comms/$id'
    | '/emergency/$id'
    | '/navigate/$id'
    | '/timeline/$id'
    | '/victim/$id'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/emergencies'
    | '/map'
    | '/network'
    | '/comms/$id'
    | '/emergency/$id'
    | '/navigate/$id'
    | '/timeline/$id'
    | '/victim/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRoute
  EmergenciesRoute: typeof EmergenciesRoute
  MapRoute: typeof MapRoute
  NetworkRoute: typeof NetworkRoute
  CommsIdRoute: typeof CommsIdRoute
  EmergencyIdRoute: typeof EmergencyIdRoute
  NavigateIdRoute: typeof NavigateIdRoute
  TimelineIdRoute: typeof TimelineIdRoute
  VictimIdRoute: typeof VictimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergencies': {
      id: '/emergencies'
      path: '/emergencies'
      fullPath: '/emergencies'
      preLoaderRoute: typeof EmergenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms/$id': {
      id: '/comms/$id'
      path: '/comms/$id'
      fullPath: '/comms/$id'
      preLoaderRoute: typeof CommsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/$id': {
      id: '/emergency/$id'
      path: '/emergency/$id'
      fullPath: '/emergency/$id'
      preLoaderRoute: typeof EmergencyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate/$id': {
      id: '/navigate/$id'
      path: '/navigate/$id'
      fullPath: '/navigate/$id'
      preLoaderRoute: typeof NavigateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$id': {
      id: '/timeline/$id'
      path: '/timeline/$id'
      fullPath: '/timeline/$id'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/victim/$id': {
      id: '/victim/$id'
      path: '/victim/$id'
      fullPath: '/victim/$id'
      preLoaderRoute: typeof VictimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRoute,
  EmergenciesRoute: EmergenciesRoute,
  MapRoute: MapRoute,
  NetworkRoute: NetworkRoute,
  CommsIdRoute: CommsIdRoute,
  EmergencyIdRoute: EmergencyIdRoute,
  NavigateIdRoute: NavigateIdRoute,
  TimelineIdRoute: TimelineIdRoute,
  VictimIdRoute: VictimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
